apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-whole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LeitnerMi/rabbitmq-poc-gitops.git
    targetRevision: main
    path: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
