apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: consumer-producer-user-permissions
spec:
  vhost: "/"
  user: "consumer-producer-user" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: hello-world
    namespace: rabbitmq-instance-main
