apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding-linz-queue-exchange
spec:
  source: topic-exchange # an existing exchange
  destination: linz-queue # an existing queue
  routingKey: "linz"
  destinationType: queue # can be 'queue' or 'exchange'
  rabbitmqClusterReference:
    name: hello-world
    namespace: rabbitmq-instance-main
