apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: topic-exchange
spec:
  name: topic-exchange # name of the exchange
  type: topic # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: hello-world
    namespace: rabbitmq-instance-main
