apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: wien-queue # name of this custom resource; does not have to the same as the actual queue name
  namespace: hello-world-cluster
spec:
  name: wien-queue # name of the queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: hello-world
